name: CI

on:
  push:
    branches: [ main ]

jobs:

  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: Action variables
        uses: Racer159/github-workflow-test@6f09313eeea1debfd91b7b1545a86ec6fad74503
        with:
          req-wo-default: 'Override'
