name: CI

on:
  push:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Action variables
        uses: Racer159/github-workflow-test@986a00690f30087b6322788b73a26e5725490c9a
        with:
          req-wo-default: 'Override'
